account_id = ""
compatibility_date = "2022-06-15"
name = "anti-bv-bot"
route = ""
type = "webpack"
webpack_config = "webpack.config.js"
workers_dev = true
zone_id = ""

[env.prod.vars]
BASEURL = "https://anti-bv-bot-prod.example.workers.dev/"
BOT_KEY = "BOT_KEY"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/wh/at/ever"
