name = "anti-bv-bot"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[env.prod.vars]
BOT_KEY = "BOT_KEY"
BASEURL = "https://anti-bv-bot-prod.example.workers.dev/"
SLACK_WEBHOOK_URL = "https://hooks.slack.com/services/wh/at/ever"
